#!/bin/bash

unmarked="/home/ian/src/unmarked"

R CMD INSTALL $unmarked
success=$?
if success==0; then
    Rscript $unmarked/inst/unitTests/runTests.R
    google-chrome /tmp/unmarked-unitTests.html
fi

